//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//https://localhost:44380/EF/Model1.tt
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceOnDTOCrud.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrudwithDTOEntities2 : DbContext
    {
        public CrudwithDTOEntities2()
            : base("name=CrudwithDTOEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllCategory> AllCategories { get; set; }
        public virtual DbSet<Auth> Auths { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<AllAuth> AllAuths { get; set; }
    }
}
